<?php
session_start();
include ('authentication.php');
?>

<!DOCTYPE html>
<!--<![endif]-->
<head>
  <?php
  include('includes/css.php');
?>
</head>
<body>

<?php
  include('includes/header.php');
?>
<section class="bg-dark text-white privacy_showCase_banner" id="showCase_banner">
  <div class="container text-center">
    <div class="row">
      <div class="col-lg-9 mx-auto">
          <h1 class="mb-2 section-heading">Terms and Conditions</h1>
      </div>
    </div>
  </div>
</section>

<section class="grey-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 mx-auto legal-info">
        <h4>1. Acceptance of Terms</h4>
          <p>Welcome to the Sikazone website. Sikazone provides its service to the user of the Sikazone website, subject to the following Terms of Service ("TOU"), which may be updated by Sikazone at any time without notice to the user. The user of the Sikazone website can review the most current version of the TOU at any time by accessing the "Terms and Conditions" link on the Sikazone website. In addition, when using particular Sikazone services, the user of the Sikazone website and Sikazone shall be subject to any posted guidelines or rules applicable to such services which may be posted from time to time. All such guidelines or rules are hereby incorporated by reference into the TOU. Sikazone also may offer other services from time to time, which may be governed by different Terms of Use. These TOU do not apply to such other services.</p>
          <h4>2. Description of Service</h4>
          <p>Sikazone currently provides users with access to a broad range of financial, investment, tax, accounting and other resources, directly, as well as through its network of contacts and service providers (the "Service"). The user of the Sikazone website also understands and agrees that the Service may include advertisements and that these advertisements may be necessary for Sikazone to provide the Service. Unless explicitly stated otherwise, any new features that augment or enhance the current Service shall be subject to the TOU. The user of the Sikazone website understands and agrees that the Service is provided "AS-IS" and that Sikazone assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.</p>
          <p>The user of the Sikazone website is responsible for obtSikazoneing access to the Service and that access may involve third party fees (such as Internet service provider or airtime charges). The user of the Sikazone website is responsible for those fees, including those fees associated with the display or delivery of advertisements. In addition, the user of the Sikazone website must provide and is responsible for all equipment necessary to access the Service.</p>
           
          <h4>3. Registration Obligations</h4> 
          <p>In consideration of the user of the Sikazone website using the Service, the user of the Sikazone website agrees to: (a) provide true, accurate, current and complete information about the user of the Sikazone website as prompted by the Service's registration form (such information being the "Registration Data") and (b) mSikazonetSikazone and promptly update the Registration Data to keep it true, accurate, current and complete. If the user of the Sikazone website provides any information that is untrue, inaccurate, not current or incomplete, or Sikazone has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Sikazone has the right to suspend or terminate the account of the user of the Sikazone website and refuse any and all current or future use of the Service (or any portion thereof).</p>

          <h4>4. Sikazone Privacy Policy</h4>
          <p>The information submitted to us will be used primarily for the purpose of creating successful matches between entrepreneurs and investors. Any information received is necessary to provide a level of certSikazonety of intent and to maximize credibility. It may also be used to provide backup that may be helpful in your desire to seek capital and/or to invest. It is also needed in order to aid with the continual improvement of the site, compile basic demographic data and to generally improve the services offered to you. The company will not sell, share or rent your confidential information to any independent third parties without your prior consent.</p>
          <p>Indexing - Please note that the title and short summary of entrepreneurs' pitches will be indexed on Google to attract more interest to your project. We therefore advise you not to include any confidential information in these sections of your pitch.</p>
          <p>Cookies - If you decide to register as an entrepreneur or angel investor with Sikazone, "cookies" are used to recognize you on subsequent visits and to make your online experience more user-friendly. "Cookies" are small bits of data that can be sent to your computer which then may be stored by your browser on your computer's hard drive. They cannot be used to retrieve data from your hard drive, email addresses or personally identifying information about you in any way. Most web browsers have features that can notify you when you receive a "cookie" or prevent "cookies" from being sent. Please note that by not accepting cookies, you will limit the website’s functionality.</p>
          <p>Security - Transaction information can be securely transmitted to the payment gateway via secure SSL connections. We do not store credit card details nor do we share customer details with any 3rd parties.</p>
          <p>Sponsor Sites - Sikazone provides links to third party sponsors. These sponsors are independent of this site and regulated by their own policies and procedures. We do not we share customer details with any 3rd parties.</p>

          <h4>5. Member Account, Password and Security</h4> 
          <p>The user of the Sikazone website is responsible for mSikazonetSikazoneing the confidentiality of the password and account, and is fully responsible for all activities that occur under its password or account. The user of the Sikazone website agrees to (a) immediately notify Sikazone of any unauthorized use of its password or account or any other breach of security, and (b) ensure that the user of the Sikazone website exits from its account at the end of each session. Sikazone cannot and will not be liable for any loss or damage arising from failure of the user of the Sikazone website to comply with this Section 5.</p>

          <h4>6. Member Conduct</h4>
          <p>The user of the Sikazone website understands that all information, data, text, software, sound, photographs, graphics, video, messages or other materials (the "Content"), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Content originated. This means that the user of the Sikazone website, and not Sikazone, is entirely responsible for all Content that the user of the Sikazone website upload, post, email, transmit or otherwise make available via the Service. Sikazone does not control the Content posted via the Service and, as such, does not guarantee the accuracy, integrity or quality of such Content. The user of the Sikazone website understands that by using the Service, the user of the Sikazone website may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will Sikazone be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the Service.</p>
          <p>If you have any questions or concerns regarding privacy, please do not hesitate to contact us at info@sikazone.com and expect a prompt response to any issues you may have.</p>
          <p>The user of the Sikazone website agrees to not use the Service to:</p>
          <ul>
            <li>upload, post, email, transmit or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libellous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable;</li>
            <li>harm minors in any way;</li>
            <li>impersonate any person or entity, including, but not limited to, a Sikazone official, forum leader, guide or host, or falsely state or otherwise misrepresent the affiliation of the user of the Sikazone website with a person or entity;</li>
            <li>forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Service;</li>
            <li>upload, post, email, transmit or otherwise make available any Content that the user of the Sikazone website do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
            <li>upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights ("Rights") of any party;</li>
            <li>upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chSikazone letters," "pyramid schemes," or any other form of solicitation, except in those areas (if any) that are expressly designated for such purpose;</li>
            <li>upload, post, email, transmit or otherwise make available any material that contSikazones software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
            <li>disrupt the normal flow of dialogue, cause a screen to "scroll" faster than other users of the Service are able to type, or otherwise act in a manner that negatively affects other users' ability to engage in real time exchanges;</li>
            <li>interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service;</li>
            <li>intentionally or unintentionally violate any applicable local, state, provincial, national or international law, including, but not limited to, regulations promulgated by any National, State, Provincial or other Securities Commission or authority, any rules of any national or other securities exchange and any regulations having the force of law;</li>
            <li>stalk or otherwise harass another; or</li>
            <li>collect or store personal data about other users.</li>
          </ul>
          <p>The user of the Sikazone website acknowledges that Sikazone does not pre-screen Content, but that Sikazone and its designees shall have the right (but not the obligation) in their sole discretion to refuse or move any Content that is available via the Service. Without limiting the foregoing, Sikazone and its designees shall have the right to remove any Content that violates the TOU or is otherwise objectionable. The user of the Sikazone website agrees that it must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, the user of the Sikazone website acknowledges that the user of the Sikazone website may not rely on any Content created by Sikazone or submitted to Sikazone, including without limitation information in Sikazone Message Boards and in all other parts of the Service.</p>
          <p>The user of the Sikazone website acknowledges and agrees that Sikazone may preserve Content and may also disclose Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the TOU; (c) respond to claims that any Content violates the rights of third-parties; or (d) protect the rights, property, or personal safety of Sikazone, its users and the public.</p>
          <p>The user of the Sikazone website understands that the technical processing and transmission of the Service, including the Content of the user of the Sikazone website, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
          <h4>7. Special Admonitions For International Use</h4>
          <p>Recognizing the global nature of the Internet, the user of the Sikazone website agrees to comply with all local rules regarding online conduct and acceptable Content. Specifically, the user of the Sikazone website agrees to comply with all applicable laws regarding the transmission of technical data exported from the country in which the user of the Sikazone website resides.</p>

          <h4>8. Content Submitted or made Avaibale For Inclusion On The Service</h4>
          <p>Sikazone does not claim ownership of Content the user of the Sikazone website submits or makes available for inclusion on the Service. However, with respect to Content the user of the Sikazone website submits or makes available for inclusion on publicly accessible areas of the Service, the user of the Sikazone website grants Sikazone the following world-wide, royalty free and non-exclusive license(s), as applicable:</p>
          <p>With respect to Content the user of the Sikazone website submits or makes available for inclusion on publicly accessible areas of Sikazone Message Boards and Sikazone Groups, the license to use, distribute, reproduce, modify, adapt, publicly perform and publicly display such Content on the Service solely for the purposes of providing and promoting the specific Sikazone Message Board or Sikazone Group to which such Content was submitted or made available. This license exists only for as long as the user of the Sikazone website elects to continue to include such Content on the Service and will terminate at the time the user of the Sikazone website removes or Sikazone removes such Content from the Service.</p>
          <p>With respect to photos, graphics, audio or video the user of the Sikazone website submits or makes available for inclusion on publicly accessible area of the Service other than Sikazone Message Boards or Sikazone Groups, the license to use, distribute, reproduce, modify, adapt, publicly perform and publicly display such Content on the Service solely for the purpose for which such Content was submitted or made available. This license exists only for as long as the user of the Sikazone website elects to continue to include such Content on the Service and will terminate at the time the user of the Sikazone website removes or Sikazone removes such Content from the Service.</p>
          <p>With respect to Content other than photos, graphics, audio or video the user of the Sikazone website submits or makes available for inclusion on publicly accessible areas of the Service other than Sikazone Message Boards or Sikazone Groups, the perpetual, irrevocable and fully sub-licensable license to use, distribute, reproduce, modify, adapt, publish, translate, publicly perform and publicly display such Content (in whole or in part) and to incorporate such Content into other works in any format or medium now known or later developed.</p>
          <p>"Publicly accessible" areas of the Service are those areas of the Sikazone's network of properties that are intended by Sikazone to be available to the general public. By way of example, publicly accessible areas of the Service would include Sikazone Message Boards and portions of Sikazone Groups that are open to both members and visitors. However, publicly accessible areas of the Service would not include portions of Sikazone Message Boards and Sikazone Groups that are limited to members, Sikazone services intended for private communication, or areas off of the Sikazone's network of properties such as portions of World Wide Web sites that are accessible through the Sikazone but are not hosted or served by the Sikazone.</p>

          <h4>9. Idemnity</h4>
          <p>The user of the Sikazone website agrees to indemnify and hold Sikazone, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of Content the user of the Sikazone website submits, posts, transmits or makes available through the Service, the use of and connection to the Service by, the user of the Sikazone website, the violation of the TOU or of any rights of another by the user of the Sikazone website.</p>

          <h4>10. No Resale of Service</h4>
          <p>The user of the Sikazone website agrees not to reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of the Service, use of the Service, or access to the Service, including any intellectual property rights of Sikazone or any person firm or corporation having posted information for availability through the Service.</p>

          <h4>11. General Practices Regarding Use and Storage</h4>
          <p>The user of the Sikazone website acknowledges that Sikazone may establish general practices and limits concerning use of the Service, including without limitation the maximum number of days that email messages, message board postings or other uploaded Content will be retSikazoneed by the Service, the maximum number of email messages that may be sent from or received by an account on the Service, the maximum size of any email message that may be sent from or received by an account on the Service, the maximum disk space that will be allotted on Sikazone's servers on behalf of the user of the Sikazone website, and the maximum number of times (and the maximum duration for which) the user of the Sikazone website may access the Service in a given period of time. The user of the Sikazone website agrees that Sikazone has no responsibility or liability for the deletion or failure to store any messages and other communications or other Content mSikazonetSikazoneed or transmitted by the Service. The user of the Sikazone website acknowledges that Sikazone reserves the right to log off accounts that are inactive for an extended period of time. The user of the Sikazone website further acknowledges that Sikazone reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.</p>

          <h4>12. Modification To Service</h4>
          <p>Sikazone reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. The user of the Sikazone website agrees that Sikazone shall not be liable to the user of the Sikazone website or to any third party for any modification, suspension or discontinuance of the Service.</p>

          <h4>13. Termination</h4>
          <p>The user of the Sikazone website agrees that Sikazone, in its sole discretion, may terminate the password, account (or any part thereof) of the user of the Sikazone website or the use of the Service, and remove and discard any Content within the Service, for any reason, including, without limitation, for lack of use or if Sikazone believes that the user of the Sikazone website has violated or acted inconsistently with the letter or spirit of the TOU or the Sikazone Acceptable Use Policy. Sikazone may also in its sole discretion and at any time discontinue providing the Service, or any part thereof, with or without notice. The user of the Sikazone website agrees that any termination of the user's access to the Service under any provision of this TOU may be effected without prior notice, and acknowledges and agrees that Sikazone may immediately deactivate or delete the user's account and all related information and files in the user's account and/or bar any further access to such files or the Service. Further, the user of the Sikazone website agrees that Sikazone shall not be liable to the user of the Sikazone website or any third-party for any termination of its access to the Service.</p>


          <h4>14. Dealings With Advertisers</h4>
          <p>The correspondence or business dealings, or participation in promotions of, advertisers found on or through the Service by the user of the Sikazone website, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between the user of the Sikazone website and such business, promoter or advertiser. The user of the Sikazone website agrees that Sikazone shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such businesses, promoters or advertisers on the Service.</p>

          <h4>15. Links</h4>
          <p>The Service may provide, or third parties may provide, links to other World Wide Web sites or resources. Because Sikazone has no control over such sites and resources, the user of the Sikazone website acknowledges and agrees that Sikazone is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products, or other materials on or available from such sites or resources. The user of the Sikazone website further acknowledges and agrees that Sikazone shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site or resource.</p>

          <h4>16. Sikazone's Proprietary Rights</h4>
          <p>The user of the Sikazone website acknowledges and agrees that the Service and any necessary software used in connection with the Service ("Software") contain proprietary and confidential information that is protected by applicable intellectual property and other laws. The user of the Sikazone website further acknowledges and agrees that Content contained in sponsor advertisements or information presented to the user of the Sikazone website through the Service or advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by Sikazone or advertisers, the user of the Sikazone website agrees not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Software, in whole or in part.</p>
          <p>Sikazone grants the user of the Sikazone website a personal, non-transferable and non-exclusive right and license to use the Service; provided that the user of the Sikazone website does not (and does not allow any third party to) copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, grant a security interest in or otherwise transfer any right in the Sikazone website, the Software or the Content. The user of the Sikazone website agrees not to modify the Software in any manner or form, or to use modified versions of Sikazone website, the Software or the Content, including (without limitation) for the purpose of obtaining unauthorized access to the Service. The user of the Sikazone website agrees not to access the Service by any means other than through the interface that is provided by Sikazone for use in accessing the Service.</p>

          <h4>17. Disclaimer of Warranties</h4>
          <p>The user of the Sikazone website expressly understands and agrees that: </p>
          <ul>
            <li> Its use of the Service is at its sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Sikazone expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement.</li>
            <li>Sikazone makes no warranty that (i) the service will meet the requirements of the user of the Sikazone website, (ii) the Service will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the Service will be accurate or reliable, (iv) the quality of any products, services, information, or other material purchased or obtained by the user of the Sikazone website through the service will meet its expectations, and (v) any errors in the Software will be corrected.</li>
            <li> Any material downloaded or otherwise obtained through the use of the Service is done at the sole discretion and risk of the user of the Sikazone website and that it will be solely responsible for any damage to its computer system or loss of data that results from the download of any such material.</li>
            <li>No advice or information, whether oral or written, obtained by the user of the Sikazone website from Sikazone or through or from the Service shall create any warranty not expressly stated in the TOU.</li>
            <li> It waives any claims it now has, or in the future may have, which gives or provides the user of the Sikazone with any cause of action whatsoever.</li>
            <li>Notwithstanding any other provisions herein, user of the Sikazone acknowledges that neither the Sikazone or its Contributors, nor their affiliates or representatives shall be liable to the user of the Sikazone, for special, incidental or consequential, special, direct or indirect damages arising directly or indirectly from any occurrence whatsoever (including without limitation loss of profits, loss of business opportunity, loss of property, of any nature whatsoever), whether or not such damages were foreseeable by the Sikazone or its Contributors or any one of them was advised of the possibility of such damages and whether otherwise arising from any contractual, tortious acts or omissions of either party or of their respective affiliates or representatives, and whether or not it had any knowledge, actual or constructive, that such damages might be incurred for having relied on the material, information, data or the Content presented or forming part of any of the Sikazone website, to make personal, medical, legal, tax, accounting, investment or financial decisions.</li>
            <li>The user of the Sikazone accepts total responsibility for any agreement, understanding or relationship the user of the Sikazone enters into with any of the Contributors. Further, the user of the Sikazone understands, acknowledges and agrees that Sikazone, in no manner whatsoever, endorses the said Contributors or whatever pitch may be presented by such Contributors and that Sikazone shall not be held liable for any claims of any nature whatsoever arising or resulting from any thesis or pitch of any of the Contributors, or from any agreement, understanding, association, investment or relationship concluded, agreed, made or established between the user of the Sikazone and any of the Contributors, of any type and for any reason whatsoever.</li>
            <li>The user of the Sikazone understands, acknowledges and agrees that the Sikazone website is designed as an educational and networking tool only, and that Sikazone is not engaged in rendering, nor is it representing itself as rendering legal, tax, financial, accounting, medical or other professional advice or opinions of any nature whatsoever to the user of the Sikazone.</li>
            <li>The user of the Sikazone hereby confirms that it qualifies as a sophisticated, accredited or professional investor", pursuant to all applicable legislation relating to the distribution and/or sale of securities.</li>
            <li>The user of the Sikazone understands, acknowledges and agrees that it is its own responsibility to obtain independent legal, tax, financial, accounting, medical or other professional advice with respect to evaluating, agreeing, establishing and/or implementing any relationship or investment based on any of the material, information or strategies presented on the Sikazone website. Further, it is highly recommended that the user of the Sikazone take adequate time to review and evaluate whatever material or information received with whichever independent professional advisors the user of the Sikazone deems appropriate.</li>
          </ul>
       

          <h4>18. Limitation of Liability</h4>
          <p>The user of the Sikazone website expressly understands and agrees that Sikazone shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if Sikazone has been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the Service; (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the Service; (iii) unauthorized access to or alteration of transmissions or data of the user of the Sikazone website; (iv) statements or conduct of any third party on the Service; (v) any agreement, understanding or relationship the user of the Sikazone enters into with any of the Contributors or any other person or entity with whom it has been put in contact through the Sikazone website; or (vi) any other matter relating to the Service.</p>

          <h4>19. Exclusion and Limitations</h4>
          <p>Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations of sections 17 and 18 may not apply to the user of the Sikazone website.</p>

          <h4>20. Special Admission For Services Relating To Financial Matters</h4>
          <p>If the user of the Sikazone website intends to create or join any service, receive or request any news, messages, alerts or other information from the Service concerning companies, stock quotes, investments or securities, it is hereby urged to read the above Sections 17 and 18 again. These Sections apply with absolute rigor to the user of the Sikazone website. In addition, for this type of information particularly, the phrase "LET THE INVESTOR BEWARE" is paramount. The Service is provided for informational purposes only, and no Content included in the Service is intended for trading or investing purposes. Sikazone and its service providers and suppliers shall not be responsible or liable for the accuracy, usefulness or availability of any information transmitted or made available via the Service, and shall not be responsible or liable for any strategy, trading or investment decisions made based on such information.</p>

          <h4>21. Notice </h4>
          <p>Notices to the user of the Sikazone website may be made via either e-mail, fax or regular mail. The Service may also provide notices of changes to the TOU or other matters by displaying notices or links to notices to the user of the Sikazone website generally on the Service.</p>

          <h4>22. Trademark Information</h4>
          <p>The Sikazone logo, the Sikazone design, and the Sikazone stylized, trademarks and service marks, and other Sikazone logos and product and service names are trademarks of Sikazone (the "Sikazone Marks"). Without Sikazone's prior permission, the user of the Sikazone website agrees not to display or use in any manner, the Sikazone Marks.</p>

          <h4>23. General Information</h4>
          <p>The TOU constitute the entire agreement between the user of the Sikazone website and Sikazone and govern the use of the Service by the user of the Sikazone website, superseding any prior agreements between the user of the Sikazone website and Sikazone. The user of the Sikazone website also may be subject to additional terms and conditions that may apply when the user of the Sikazone website uses affiliate services, third-party content or third-party software. The TOU and the relationship between the user of the Sikazone website and Sikazone shall be governed by the laws in force in the United Kingdom, without regard to its conflict of law provisions. The user of the Sikazone website and Sikazone agree to submit to the personal and exclusive jurisdiction of the courts located within the country of Great Britain. </p>
          <p>The failure of Sikazone to exercise or enforce any right or provision of the TOU, the Sikazone subscription documentation Terms and Conditions or the Sikazone Acceptable Use Policy shall not constitute a waiver of such right or provision. If any provision of the TOU, the Sikazone subscription documentation Terms and Conditions or the Sikazone Acceptable Use Policy is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, and the other provisions of the TOU, the Sikazone subscription documentation Terms and Conditions and the Sikazone Acceptable Use Policy remsin in full force and effect. The user of the Sikazone website agrees that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the TOU, the Sikazone subscription documentation Terms and Conditions and the Sikazone Acceptable Use Policy must be filed within one (1) year after such claim or cause of action arose or be forever barred. The section titles in the TOU are for convenience only and have no legal or contractual effect.</p>

          <h4>24. Acceptable Use</h4>
          <p>For purposes of this Acceptable Use Policy ("AUP"), a "Customer" is defined to include any organization, individual, company or other entity with which Angel Investment Network Ltd (Sikazone) has entered into any agreement or contract for the supply of services, including through the Sikazone website. A Customer shall also be responsible for the use of the Sikazone website by any subsidiaries, affiliates, partners, Authorized Staff, suppliers, clients, or any other person gaining access to the Sikazone website in any manner whatsoever, that directly or indirectly utilize the Sikazone website provided to the Customer.</p>
          <p>The Customer may only use the Sikazone website for lawful purposes. The use of the Sikazone website in violation of any local or international legislation or regulation is prohibited. This includes, but is not limited to, transmission of proprietary or copyright material without the consent of the owner, material legally judged to be threatening, offensive, or obscene, and third party material protected by patent, trade secret or any other type of intellectual property right, whether or not the Customer was aware of the content of the material or of the relevant law.</p>
          <p>Sikazone will fully co-operate with investigations of suspected criminal violations and violations of systems or network security under the leadership of law enforcement authorities.</p>
          <p>Use of any information obtained via the Sikazone website is at Customers' own risk. Sikazone is not responsible for the accuracy, quality, or content of information obtained through NS Products.</p>
          <p>All Sikazone services are for end-user use only and may not be resold to third-parties without providing end-user information to Sikazone.</p>
          <p>The Customer will indemnify and hold Sikazone harmless from any claim brought by third parties alleging that use of the Sikazone website by the Customer has infringed any applicable local or international legislation or regulation. The Customer shall defend and pay all costs, damages, awards, fees (including reasonable legal fees) and final judgments awarded against Sikazone arising from such claims. The Customer shall immediately give Sikazone written notice of any claim the Customer is involved with or aware of. Should the Customer fail to do so, Sikazone may defend such claims at the Customer's sole cost.</p>

          <p>Sikazone will cooperate with any law enforcement authorities having jurisdiction to discourage and resist abuses of acceptable use policies. Sikazone reserves the right to take corrective action upon notification to Sikazone of unacceptable use by the Customer. Sikazone reserves the right, at its discretion and without notice, to remove any material or data and to block the use of the network for one or more users.</p>
          <p>The Customer may not circumvent user authentication or security of any host, network, or account (referred to as "cracking" or "hacking"), reverse engineer, decompile, deconstruct any programming, nor interfere with service to any user, host, or network (referred to as "denial of service attacks").</p>
          <p>The Customer is forbidden to send e-mail to any person who does not wish to receive it. It is explicitly prohibited to send unsolicited bulk mail messages ("junk mail" or "spam") of any kind (commercial advertising, financial and investment promotions, political tracts, announcements, etc.) or to post the same or similar messages to large numbers of newsgroups (excessive cross-posting or multiple-posting, also known as "USENET spam"). A Customer caught spamming on the Sikazone, or who persist in the mass distribution of unsolicited e-mail messages, will be dealt with immediately in accordance with this AUP.</p>
          <p>The Sikazone website may be used by the Customer to link into other networks worldwide and the Customer agrees to conform to the acceptable use policies of these networks. The Customer agrees, through its own operations, not to cause disturbances, outages or other problems which may affect Sikazone's network or network based equipment, or which may adversely affect Sikazone's ability to provide services.</p>
          <p>Sikazone reserves the right to prohibit activities that violate this AUP or may damage its reputation.</p>
          <p>Sikazone will generally not monitor private electronic mail messages sent or received by its Customers but may conduct reasonable investigation of a Customer (i) if required by law or (ii) upon reasonable suspicion of a violation of this AUP to determine if there has been a violation or (iii) when public safety may require it. Sikazone may at all time monitor usage of the Sikazone website electronically to determine if it is operating satisfactorily.</p>
          <p>Sikazone may disclose its Customers' information or information transmitted by means of its facilities (i) to comply with legal requirements or (ii) where necessary to protect Sikazone and others from harm or (iii) where such disclosure is necessary to the proper operation of the Sikazone website.</p>
          <p>The Customer acknowledges that Sikazone is unable to exercise control over the content of information passing through its facilities or carried as a result of supplying the Sikazone website and is therefore not responsible for that content.</p>
          <p>Sikazone reserves the right, at its discretion and without notice, to automatically filter, disconnect and/or deny access to any Customer who violates this policy. This remedy shall also be applied when the Customer has engaged in any of the foregoing activities by using the service of another provider and, channelling such activities through a Sikazone account, re-mailer, or otherwise through the Sikazone website, or using a Sikazone account as a mail drop for responses or otherwise using the services of another provider for the purpose of facilitating the foregoing activities, if such use of another party's service could reasonably be expected to adversely affect the Sikazone website. Sikazone reserves the right, where feasible, to implement technical mechanisms which block multiple postings as described above before they are forwarded or otherwise sent to their intended recipients.</p>
          <p>Violation of this AUP (direct or indirect, including by a third party) entitles Sikazone to remove immediately the offending material, establish immediate or temporary filtering, deny access, suspend or terminate one or more subscriptions to the Sikazone website, or take any other appropriate action, as determined by Sikazone in its sole discretion, in addition to any remedies provided by any agreement to provide access to the Sikazone website. Sikazone may give notice of violations but Sikazone reserves the right to act without notice when necessary, as determined by Sikazone in its sole discretion. Nothing in this AUP is to be construed to limit Sikazone's actions or remedies in any way with respect to any of the foregoing activities, and Sikazone reserves the right to take any additional actions it may deem appropriate with respect to such activities, including without limitation, taking action to recover the cost of identifying offenders and terminating their access to the Sikazone website, and charging to cover Sikazone's costs in the event of such termination of access or like situation. Sikazone may co-operate with other service providers to discourage and resist abuses of acceptable use policies. Sikazone reserves the right to take corrective action upon notification to Sikazone of unacceptable use on other networks. The Sikazone website may be linked to other networks world-wide and the Customer agrees to conform to the acceptable use policies of these networks. The Customer agrees, through its operations, not to cause disturbances, outages or other problems which may affect Sikazone's or any other network or network based equipment, or which may adversely affect Sikazone's ability to provide access to the Sikazone website.</p>
          <p>Nothing contained in this AUP shall be construed to limit Sikazone's actions or remedies in any way with respect to any of the foregoing activities, and Sikazone reserves the right to take any and all additional actions it may deem appropriate with respect to such activities, including without limitation, taking action to recover the costs and expenses of identifying offenders and removing them from the Sikazone website, and levying cancellation charges to cover Sikazone's costs in the event of disconnection of dedicated access for the causes outlined above. In addition, Sikazone reserves at all times all rights and remedies available to it with respect to such activities at law or in equity.</p>
          <p>Customer will indemnify and hold Sikazone harmless from any claim brought by third parties relating to the Customer's use of the Sikazone website. The Customer must defend and pay all damages and costs (including legal fees) arising from such claims. The Customer must immediately notify Sikazone of any claim or potential claim, within the Customer's knowledge, involving the Customer related to the Sikazone website. Failure to do so gives Sikazone the right to defend such claims at Customer's sole cost and expense.</p>
          <p>Sikazone is committed to providing quality service to all of its Customers. While the AUP may appear harsh, Sikazone believes it is necessary to ensure that it is able to provide professional, efficient, stable service within an environment of security and trust which its Customers may require and come to expect from an organization such as Sikazone.</p>
          <p>This AUP is subject to change. Please contact us with any questions regarding the policy or to report a breach of AUP.</p>
       

       </div>

    </div>
  </div>    
</section>


<footer class="bg-dark text-light">
    <div class="container">
      <div class="row">
          <div class="col-lg-3 footer-col">
            <img src="images/logo-light.png" alt="logo">
            <p class=" mt-2">Back in 2004, lots of people were trying to start businesses – many with brilliant ideas. But they were struggling to find the seed funding necessary to grow; and the best investors to guide their growth.</p>
          </div>
          <div class="col-lg-3 pl-5">
            <h5>Legal Info.</h5>
            <ul>
              <li><a href="about-us.html">About</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Terms & Conditions</a></li>
              <li><a href="contact-us.html">Contact Us</a></li>
            </ul>
          </div>
          <div class="col-lg-3 pl-5">
            <h5>Navigation</h5>
            <ul class="list-inline ">
                <li><a href="find-investor.html">Find Investor</a></li>
                <li><a href="#">Find Entrepreneurs</a></li>
                <li><a href="#">Find Lender</a></li>
                <li><a href="#">Find Borrower</a></li>
            </ul>
          </div>
          <div class="col-lg-3 pl-5">
            <h5>Contact Info</h5>
                <ul class="list-inline contact-details">
                    <li><i class="fa fa-map-marker" aria-hidden="true"></i> United States of Kingdom, UK</li>
                    <li><a href="#"><i class="fa fa-envelope"></i>Info@sikazone.com</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i> +00 193 (763)99</a></li>
                </ul>
                <ul class="socials mt-3">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                </ul>
          </div>
      </div>    
    </div>

    <div class="footer_bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center my-auto" >
                   <p>Copyright © 2019 SikaZone All Rights Reserved.</p>
                </div>
            </div>    
        </div>
    </div>
</footer>

<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>

</body>
</html>